### ISSUE TITLE
In the fullness of time, support double quotes in fates

### ISSUE THREAD

**Issue by matthewjweaver** [grahams/fatewheel#22]
https://github.com/grahams/fatewheel/blob/e32042fa73f12666488e38f2005821a9d432037b/index.js#L201

I suspect setting a local variable to JSON.stringify(newFate.toUpperCase()) here, and using it thereafter for the new fate text, will fix the double quote funny business.

it'll still break on single quotes, but whatever this is aunty we're talking about here

**Comment by grahams** [comment]
Fixed in https://github.com/grahams/fatewheel/pull/23
